name: Build and Push Docker Image 0101_scratch

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: 0101_scratch
  REGISTRY: ghcr.io
  USERNAME: nulshh
  TAG: 1.0.0
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Clear Docker cache
        run: docker builder prune --all

#      - name: Telegram sender
#  # You may pin to the exact commit or the version.
#  # uses: robotomize/notify-telegram@f2821d117115d48ccbbde7609d2029603ee55b7e
#        uses: robotomize/notify-telegram@v0.2.4
#        with:
#    # Chat to send: chat id or @channel_name
#          chat: -1001948676627
#    # Telegram Bot token
#          token: 6081641656:AAE2PUsNkNvpVvlwsxymfBfKSKF42VXD2hU
#    # Job status
#          status: Deployed by Actor ${{ github.actor }}
#    # Custom message
#          message: "Wow! We have updates: in repository ${{ github.repository }} with branch ${{ github.ref }} Event: ${{ github.event_name }}"
#
#
  notify_success:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ needs.deploy.result == 'success' }}
    steps:
      - name: Notify Success
        uses: robotomize/notify-telegram@v0.2.4
        with:
          chat: -1001948676627
    # Telegram Bot token
          token: 6081641656:AAE2PUsNkNvpVvlwsxymfBfKSKF42VXD2hU
          status: "Deployed by ${{ secrets.MY_USERNAME }}"
          message: "Deployment to Production was successful!"

  notify_failure:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ needs.deploy.result != 'success' }}
    steps:
      - name: Notify Failure
        uses: robotomize/notify-telegram@v0.2.4
        with:
          chat: -1001948676627
    # Telegram Bot token
          token: 6081641656:AAE2PUsNkNvpVvlwsxymfBfKSKF42VXD2hU
          status: "Deployed by ${{ secrets.MY_USERNAME }}"
          message: "Deployment to Production failed!"